package engine

import (
	"github.com/arthurgray2k/The_Stars_Like_Dust/internal/persona"
)

// Scene defines a dramatic situation with context, location, actor, and candidate options.
type Scene struct {
	Index          int                       `json:"index"`
	Title          string                    `json:"title"`
	Location       string                    `json:"location"`
	Description    string                    `json:"description"`
	PrimaryActor   string                    `json:"primary_actor"`
	Options        []persona.CandidateAction `json:"options"`
	NarrativeEvent string                    `json:"narrative_event"`
}

// BuildEpisodeScenes generates the narrative sequence based on chosen character POV.
func BuildEpisodeScenes(pov string) []Scene {
	switch pov {
	case "artemisia_hinriad":
		return buildArtemisiaScenes()
	case "gillbret_hinriad":
		return buildGillbretScenes()
	case "sander_jonti":
		return buildJontiScenes()
	case "simok_aratap":
		return buildSimokAratapScenes()
	case "hinrik_hinriad":
		return buildHinrikScenes()
	case "biron_farrill":
		fallthrough
	default:
		return buildBironScenes()
	}
}

func buildBironScenes() []Scene {
	return []Scene{
		{
			Index:        1,
			Title:        "The Dormitory Trap on Earth",
			Location:     "University of Earth, Sector Solar-0",
			Description:  "A concealed radiation capsule ticks silently in Biron Farrill's dormitory ventilation duct. An urgent anonymous warning buzzes on his communicator.",
			PrimaryActor: "biron_farrill",
			Options: []persona.CandidateAction{
				{
					ID:             "biron_evacuate_earth",
					Description:    "Heed warning, bypass local police, and board cargo transport to Rhodia",
					TacticalType:   "COVERT",
					Keywords:       []string{"avenge", "escape", "rebellion", "widemos"},
					BaseRisk:       0.3,
					DialoguePrompt: "My father taught me that survival precedes victory. Earth is compromised; Rhodia holds the answers.",
				},
				{
					ID:             "biron_confront_police",
					Description:    "Report assassination attempt to Earth Security Commissioner",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"police", "law", "inquiry"},
					BaseRisk:       0.8,
					DialoguePrompt: "Someone planted radioactive poison in my quarters. Who authorized this?",
				},
				{
					ID:             "biron_investigate_bomb",
					Description:    "Dismantle ventilation casing to trace the isotopic signature and origin of the bomb capsule",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"investigate", "isotopic", "bomb", "truth", "clues"},
					BaseRisk:       0.4,
					DialoguePrompt: "This radiation decay signature isn't local. Whoever set this trap had access to military isotopes.",
				},
				{
					ID:             "biron_ambush_watchers",
					Description:    "Draw ion pistol and ambush the surveillance agents monitoring outside the dormitory",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"ambush", "fight", "assassins", "pistol", "avenge"},
					BaseRisk:       0.65,
					DialoguePrompt: "You thought you caught me sleeping! Drop your blasters and talk!",
				},
			},
		},
		{
			Index:        2,
			Title:        "Infiltrating the Directorate of Rhodia",
			Location:     "Hinriad Palace Grounds, Rhodia",
			Description:  "Biron arrives on Rhodia. Director Hinrik appears to tremble in panic, while his daughter Artemisia observes Biron with intense scrutiny.",
			PrimaryActor: "biron_farrill",
			Options: []persona.CandidateAction{
				{
					ID:             "biron_alliance_artemisia",
					Description:    "Propose covert pact with Lady Artemisia to resist Tyranni subjugation",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"rebellion", "honor", "alliance", "constitutional"},
					BaseRisk:       0.35,
					DialoguePrompt: "Lady Artemisia, the Tyranni took my father's life and seek to trade your freedom. We must stand together.",
				},
				{
					ID:             "biron_demand_hinrik",
					Description:    "Publicly demand Director Hinrik explain his subservience to Tyrann",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"confront", "cowardice", "demand", "avenge", "widemos"},
					BaseRisk:       0.75,
					DialoguePrompt: "Does the proud House of Hinriad grovel before desert barbarians?",
				},
				{
					ID:             "biron_shadow_palace",
					Description:    "Slip into the servants' passage to evade the Rhodian guards and eavesdrop on court discussions",
					TacticalType:   "COVERT",
					Keywords:       []string{"shadow", "stealth", "infiltrate", "eavesdrop"},
					BaseRisk:       0.4,
					DialoguePrompt: "Keep to the shadows. If Hinrik is compromised, we cannot walk through the front doors.",
				},
				{
					ID:             "biron_probe_hinrik_eccentricities",
					Description:    "Analyze Hinrik's apparent nervous tics to discern whether they mask hidden calculation",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"scrutinize", "psychology", "inquiry", "mask"},
					BaseRisk:       0.3,
					DialoguePrompt: "Look at the Director's eyes when he mentions the archive. His panic is too rehearsed.",
				},
			},
		},
		{
			Index:        3,
			Title:        "Seizure of The Remembrance",
			Location:     "Rhodia Imperial Spaceport, Hangar 9",
			Description:  "Accompanied by Artemisia and Gillbret, Biron enters the military hangar where the prototype cruiser Remembrance is prepped for flight.",
			PrimaryActor: "biron_farrill",
			Options: []persona.CandidateAction{
				{
					ID:             "biron_pilot_breakout",
					Description:    "Override hangar blast doors and initiate atmospheric breakout into hyper-space",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"breakout", "pilot", "escape", "widemos"},
					BaseRisk:       0.4,
					DialoguePrompt: "Hold on to the acceleration couches! We break orbit now!",
				},
				{
					ID:             "biron_stealth_launch",
					Description:    "Forge civilian clearance codes and execute sub-orbital glide",
					TacticalType:   "COVERT",
					Keywords:       []string{"stealth", "codes", "glide"},
					BaseRisk:       0.5,
					DialoguePrompt: "Clearance transmitter engaged. Keep all non-essential radiation dampened.",
				},
				{
					ID:             "biron_parley_hangar_guards",
					Description:    "Invoke the Hinriad family crest to demand immediate port clearance from the technicians",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"clearance", "authority", "parley", "crest"},
					BaseRisk:       0.35,
					DialoguePrompt: "Stand aside in the name of the Directorate! Lady Artemisia commandeers this vessel on urgent state business.",
				},
				{
					ID:             "biron_analyze_ship_telemetry",
					Description:    "Inspect the prototype avionics and hyperspace jump log entries before ignition",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"avionics", "telemetry", "diagnostics", "systems"},
					BaseRisk:       0.25,
					DialoguePrompt: "These hyperdrive relays have been calibrated for an unfamiliar nebular jump corridor. Someone pre-programmed this ship.",
				},
			},
		},
		{
			Index:        4,
			Title:        "Rendezvous with the Autarch at Lingane",
			Location:     "Deep Space Border, Lingane Sector",
			Description:  "Sander Jonti arrives aboard his armed flagship, offering fuel, arms, and alliance, while demanding complete command over the expedition to the Horsehead Nebula.",
			PrimaryActor: "biron_farrill",
			Options: []persona.CandidateAction{
				{
					ID:             "biron_scrutinize_jonti",
					Description:    "Accept logistics but maintain independent navigational command and probe Jonti's motives",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"betrayal", "scrutinize", "widemos", "independence"},
					BaseRisk:       0.3,
					DialoguePrompt: "We welcome Lingane's fuel, Autarch, but Remembrance charts her own course.",
				},
				{
					ID:             "biron_surrender_command",
					Description:    "Surrender navigational control fully to Jonti's military tacticians",
					TacticalType:   "DEFENSIVE",
					Keywords:       []string{"surrender", "subservience", "trust"},
					BaseRisk:       0.85,
					DialoguePrompt: "Take the bridge, Autarch. We place our fates in Lingane's hands.",
				},
				{
					ID:             "biron_stand_firm_jonti",
					Description:    "Rebuff Jonti's imperious demands and assert Widemos martial leadership",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"defiance", "command", "widemos", "strength"},
					BaseRisk:       0.5,
					DialoguePrompt: "Lingane does not give orders to Widemos, Autarch! We lead this expedition or fly alone.",
				},
				{
					ID:             "biron_diplomatic_compromise_jonti",
					Description:    "Negotiate a power-sharing mutual defense accord between Lingane and Rhodia",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"treaty", "compromise", "alliance", "accord"},
					BaseRisk:       0.25,
					DialoguePrompt: "Let us form an equal council of war, Autarch. United we stand against the Tyranni; divided we fall.",
				},
			},
		},
		{
			Index:        5,
			Title:        "The Revelation of the Ancient Document",
			Location:     "The Heart of the Horsehead Nebula",
			Description:  "Aratap's imperial fleet springs the trap, tracking Remembrance via sub-ether transponder. In the climactic confrontation, Jonti's betrayal of Widemos is exposed, and Director Hinrik's secret vault discloses the ancient Pre-Atomic Earth document: the democratic Constitution.",
			PrimaryActor: "biron_farrill",
			Options: []persona.CandidateAction{
				{
					ID:             "biron_proclaim_constitution",
					Description:    "Unmask Jonti's treachery, challenge Aratap's imperial order, and proclaim the constitutional federation of free worlds",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"constitutional", "liberty", "federation", "truth", "overthrow"},
					BaseRisk:       0.2,
					DialoguePrompt: "The weapon is not a death ray, Commissioner Aratap! It is the constitutional blueprint of government by the consent of the governed—an idea that will outlive the Khanate!",
				},
				{
					ID:             "biron_fire_blasters",
					Description:    "Engage full blaster batteries against Aratap's capital dreadnought",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"fire", "batteries", "avenge", "widemos", "blasters"},
					BaseRisk:       0.85,
					DialoguePrompt: "Open fire on all forward batteries! Avenge Widemos!",
				},
				{
					ID:             "biron_covert_exfiltration",
					Description:    "Deploy electronic dust shrouds and exfiltrate the constitutional parchment into the deep-space void",
					TacticalType:   "COVERT",
					Keywords:       []string{"covert", "exfiltrate", "stealth", "shroud", "parchment", "constitutional", "rebellion"},
					BaseRisk:       0.45,
					DialoguePrompt: "Activate the carbon chaff! If the Khanate takes this ship, the parchment will already be light-years away in safe hands.",
				},
				{
					ID:             "biron_probe_nebula_archives",
					Description:    "Run deep spectrometric scans on the ancient coordinates to locate the hidden pre-atomic vault world",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"probe", "spectrometry", "archives", "coordinates", "vault", "rebellion", "constitutional"},
					BaseRisk:       0.35,
					DialoguePrompt: "Look at the telemetry readings! The parchment is an index key pointing straight to the Pre-Atomic sanctuary world!",
				},
			},
		},
	}
}

func buildArtemisiaScenes() []Scene {
	return []Scene{
		{
			Index:        1,
			Title:        "The Dynastic Ultimatum",
			Location:     "Directorate Chambers, Rhodia",
			Description:  "Artemisia is confronted with an imperial decree ordering her marriage to a decrepit Tyranni warlord to secure Rhodia's appeasement.",
			PrimaryActor: "artemisia_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "arte_refuse_decree",
					Description:    "Defy the marriage decree and activate covert emergency escape contingency",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"defiance", "liberty", "autonomy", "refuse"},
					BaseRisk:       0.3,
					DialoguePrompt: "I am a daughter of Hinriad, not livestock to barter for the Khan's favor.",
				},
				{
					ID:             "arte_submit_court",
					Description:    "Acquiesce to the court ministers and accept the imperial match",
					TacticalType:   "DEFENSIVE",
					Keywords:       []string{"submit", "appeasement", "marriage"},
					BaseRisk:       0.8,
					DialoguePrompt: "If Rhodia demands my sacrifice, I shall submit.",
				},
				{
					ID:             "arte_covert_escape",
					Description:    "Slip out through the royal private catacombs into the lower city",
					TacticalType:   "COVERT",
					Keywords:       []string{"escape", "catacombs", "covert", "stealth"},
					BaseRisk:       0.35,
					DialoguePrompt: "Let the ministers argue with an empty chair. I will not be in Rhodia by morning.",
				},
				{
					ID:             "arte_probe_minister_motives",
					Description:    "Cross-examine the court advisors to identify which minister accepted Tyrann bribes",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"interrogate", "advisors", "bribe", "treason"},
					BaseRisk:       0.25,
					DialoguePrompt: "Which of you received promissory drafts from the Khan's treasury to draft this decree?",
				},
			},
		},
		{
			Index:        2,
			Title:        "The Widemos Interception",
			Location:     "Palace Private Gardens, Rhodia",
			Description:  "Artemisia intercepts the fugitive Biron Farrill slipping past the palace guards.",
			PrimaryActor: "artemisia_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "arte_enlist_biron",
					Description:    "Enlist Biron's tactical strength and offer access to cruiser Remembrance",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"alliance", "escape", "resistance", "cruiser"},
					BaseRisk:       0.35,
					DialoguePrompt: "You are Farrill of Widemos. You need a starship, and I need a pilot. Shall we negotiate?",
				},
				{
					ID:             "arte_handover_biron",
					Description:    "Summon palace guards to arrest the Widemos fugitive",
					TacticalType:   "DEFENSIVE",
					Keywords:       []string{"guards", "arrest", "betrayal"},
					BaseRisk:       0.85,
					DialoguePrompt: "Guards! An intruder in the inner courtyard!",
				},
				{
					ID:             "arte_test_biron_resolve",
					Description:    "Interrogate Biron on his military credentials and Earth political connections",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"test", "credentials", "inquiry", "resolve"},
					BaseRisk:       0.3,
					DialoguePrompt: "Before I trust you with Remembrance, prove you possess your father's strategic mind.",
				},
				{
					ID:             "arte_covert_cloak_biron",
					Description:    "Disguise Biron as a Hinriad house engineer to smuggle him past orbital checkpoints",
					TacticalType:   "COVERT",
					Keywords:       []string{"disguise", "engineer", "smuggle", "stealth"},
					BaseRisk:       0.25,
					DialoguePrompt: "Put on this technician's tunic. To the garrison, you are merely my avionics specialist.",
				},
			},
		},
		{
			Index:        3,
			Title:        "Astronavigation into the Void",
			Location:     "Bridge of The Remembrance, Hyperspace",
			Description:  "Artemisia calculates complex hyperspace micro-jumps skirting Tyranni sensor pickets around the Horsehead Nebula.",
			PrimaryActor: "artemisia_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "arte_calculate_jump",
					Description:    "Plot high-precision jump through dark dust corridors relying on Gillbret's sensory logs",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"navigation", "corridor", "precision", "nebula"},
					BaseRisk:       0.3,
					DialoguePrompt: "Hold tight. We are diving directly through the dust curtain.",
				},
				{
					ID:             "arte_high_thrust_burn",
					Description:    "Force full acceleration through the sensor picket to punch past patrol corvettes",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"acceleration", "burn", "punch", "speed"},
					BaseRisk:       0.6,
					DialoguePrompt: "Redline the sub-light drives! Let them try to match our acceleration vector!",
				},
				{
					ID:             "arte_silent_running",
					Description:    "Cut main reaction drives and drift on gravimetric currents past patrol sensors",
					TacticalType:   "COVERT",
					Keywords:       []string{"drift", "silent", "gravimetric", "stealth"},
					BaseRisk:       0.35,
					DialoguePrompt: "Kill all auxiliary power. Let the nebula's gravitational tide carry us through.",
				},
				{
					ID:             "arte_rally_crew",
					Description:    "Inspire the crew and passengers to maintain cohesion amidst hyperspace turbulence",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"rally", "morale", "unity", "courage"},
					BaseRisk:       0.2,
					DialoguePrompt: "Steady yourselves! Rhodia's survival rides with us through the storm.",
				},
			},
		},
		{
			Index:        4,
			Title:        "Repelling the Autarch's Ambition",
			Location:     "Wardroom, The Remembrance",
			Description:  "Sander Jonti attempts to persuade Artemisia to unite Rhodia and Lingane under his autocratic banner.",
			PrimaryActor: "artemisia_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "arte_reject_jonti",
					Description:    "Denounce Jonti's predatory ambition and reaffirm Rhodian sovereign independence",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"autonomy", "reject", "sovereignty", "democracy"},
					BaseRisk:       0.25,
					DialoguePrompt: "You do not want a partner, Autarch; you want a vassal planet. Rhodia will never bow to Lingane.",
				},
				{
					ID:             "arte_arm_internal_defenses",
					Description:    "Prime shipboard defense turrets and warn Jonti against any hostile takeover attempt",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"turrets", "defend", "warning", "hostile"},
					BaseRisk:       0.55,
					DialoguePrompt: "One threatening gesture toward my helm, Autarch, and the wardroom security grid fires.",
				},
				{
					ID:             "arte_slip_tracker_jonti",
					Description:    "Plant a clandestine audio bug in Jonti's communications transceiver",
					TacticalType:   "COVERT",
					Keywords:       []string{"bug", "transceiver", "covert", "intelligence"},
					BaseRisk:       0.3,
					DialoguePrompt: "A slight magnetic tap against his communicator... let us hear what Lingane whispers.",
				},
				{
					ID:             "arte_expose_jonti_logistics",
					Description:    "Examine Jonti's fuel manifests to deduce where his fleet staged before the rendezvous",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"manifests", "logistics", "deduce", "staging"},
					BaseRisk:       0.2,
					DialoguePrompt: "Your fuel isotopes don't come from Lingane, Jonti. Where did you truly acquire this propellant?",
				},
			},
		},
		{
			Index:        5,
			Title:        "The Vindication of Hinrik",
			Location:     "Flagship Council Chamber, Nebula Sector",
			Description:  "Aratap confronts the prisoners. Hinrik's true master plan is revealed, proving his apparent cowardice was a 30-year sacrifice.",
			PrimaryActor: "artemisia_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "arte_embrace_legacy",
					Description:    "Stand beside her father and proclaim Rhodia's leadership in the democratic federation",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"legacy", "constitutional", "liberty", "reverence"},
					BaseRisk:       0.2,
					DialoguePrompt: "Father, forgive my blindness. Today Rhodia gives humanity the gift of free governance.",
				},
				{
					ID:             "arte_challenge_aratap_navy",
					Description:    "Defiantly order Remembrance's automated combat drones to lock onto the Tyranni bridge",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"challenge", "drones", "defiance", "lock"},
					BaseRisk:       0.7,
					DialoguePrompt: "Target their primary bridge! Even surrounded, Rhodia will not surrender on its knees!",
				},
				{
					ID:             "arte_secure_constitutional_cache",
					Description:    "Transmit encrypted copies of the Pre-Atomic Constitution across all regional civilian relay buoys",
					TacticalType:   "COVERT",
					Keywords:       []string{"transmit", "cache", "encrypted", "relay", "broadcast"},
					BaseRisk:       0.3,
					DialoguePrompt: "Broadcast the charter across all fifty sectors! The idea is already free.",
				},
				{
					ID:             "arte_analyze_ancient_charter",
					Description:    "Study the ancient Terran articles to synthesize an immediate interstellar treaty framework",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"charter", "analyze", "constitutional", "framework"},
					BaseRisk:       0.15,
					DialoguePrompt: "Article One: Government by the consent of the governed. Here lies the foundation of our new star league.",
				},
			},
		},
	}
}

func buildSimokAratapScenes() []Scene {
	return []Scene{
		{
			Index:        1,
			Title:        "The Widemos Assessment",
			Location:     "Tyrannic Imperial Headquarters, Rhodia",
			Description:  "Commissioner Aratap reviews intelligence reports following the execution of the Rancher of Widemos. He analyzes potential insurrectionary tremors.",
			PrimaryActor: "simok_aratap",
			Options: []persona.CandidateAction{
				{
					ID:             "aratap_deploy_tracer",
					Description:    "Authorize clandestine installation of sub-ether transponder on cruiser Remembrance",
					TacticalType:   "COVERT",
					Keywords:       []string{"tracer", "surveillance", "order", "calculating"},
					BaseRisk:       0.2,
					DialoguePrompt: "Do not execute Farrill's son. Let him run. He will navigate where our scout probes cannot follow.",
				},
				{
					ID:             "aratap_interrogate_suspects",
					Description:    "Order military arrest and aggressive interrogation of Widemos retainers across Rhodia",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"interrogate", "arrest", "iron", "crackdown"},
					BaseRisk:       0.6,
					DialoguePrompt: "Round up every Widemos sympathizer. Let them feel the weight of imperial justice.",
				},
				{
					ID:             "aratap_diplomatic_parley",
					Description:    "Convene Rhodian noble houses to offer amnesty in return for naming rebel sympathizers",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"amnesty", "nobility", "parley", "negotiation"},
					BaseRisk:       0.3,
					DialoguePrompt: "The Khanate values order over vengeance. Hand over the conspirators and your fiefs remain secure.",
				},
				{
					ID:             "aratap_analyze_rebel_patterns",
					Description:    "Collate fifty years of smuggling data to isolate the theoretical coordinates of the rebel planet",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"analytics", "smuggling", "patterns", "data"},
					BaseRisk:       0.15,
					DialoguePrompt: "Every rebellion leaves statistical footprints in logistics. Let the data guide the cruisers.",
				},
			},
		},
		{
			Index:        2,
			Title:        "Interrogating the Director",
			Location:     "Audience Hall, Rhodia",
			Description:  "Aratap questions Hinrik of Rhodia, observing his nervous tics and medical complaints.",
			PrimaryActor: "simok_aratap",
			Options: []persona.CandidateAction{
				{
					ID:             "aratap_feign_satisfaction",
					Description:    "Politely humor Hinrik's stammering while noting subtle irregularities in archival access logs",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"patience", "rationality", "surveillance"},
					BaseRisk:       0.15,
					DialoguePrompt: "Your health concerns are noted, Director. Continue your archival reorganizations at your leisure.",
				},
				{
					ID:             "aratap_threaten_garrison",
					Description:    "Directly threaten military occupation of the palace if Hinrik does not surrender the suspect",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"threaten", "occupation", "ultimatum", "garrison"},
					BaseRisk:       0.55,
					DialoguePrompt: "One more nervous stammer, Hinrik, and my legionnaires will dismantle this palace wall by wall.",
				},
				{
					ID:             "aratap_clandestine_tap",
					Description:    "Plant sub-micron audio bugs inside the Directorate archive terminals",
					TacticalType:   "COVERT",
					Keywords:       []string{"tap", "microphones", "surveillance", "archive"},
					BaseRisk:       0.2,
					DialoguePrompt: "Install the taps on the archive data conduits. When the fool drops his mask, we will hear it.",
				},
				{
					ID:             "aratap_formal_treaty_review",
					Description:    "Remind Hinrik of Rhodia's treaty obligations under the Khanate Protectorate",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"treaty", "protectorate", "obligations", "protocol"},
					BaseRisk:       0.25,
					DialoguePrompt: "The Khan protects Rhodia in exchange for transparency, Director. Honor the concordat.",
				},
			},
		},
		{
			Index:        3,
			Title:        "Trailing the Nebula Expedition",
			Location:     "Command Deck, Imperial Dreadnought",
			Description:  "The sub-ether tracer signals Remembrance entering the Horsehead Nebula alongside Lingane's fleet.",
			PrimaryActor: "simok_aratap",
			Options: []persona.CandidateAction{
				{
					ID:             "aratap_shadow_fleet",
					Description:    "Maintain silent sensor distance and let conspirators locate coordinates before intercepting",
					TacticalType:   "COVERT",
					Keywords:       []string{"order", "shadow", "calculating"},
					BaseRisk:       0.2,
					DialoguePrompt: "Hold fire. Let them reach the center. When they drop anchor, we close the net.",
				},
				{
					ID:             "aratap_blockade_corridor",
					Description:    "Deploy battle squadrons across the nebula perimeter to seal off all escape hyperspace corridors",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"blockade", "squadrons", "containment", "overwhelm"},
					BaseRisk:       0.4,
					DialoguePrompt: "Form battle lines across hyper-vectors alpha through delta. None escape the nebula.",
				},
				{
					ID:             "aratap_hail_lingane_flagship",
					Description:    "Transmit an imperial summons to Sander Jonti offering joint governance terms",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"hail", "terms", "alliance", "diplomacy"},
					BaseRisk:       0.3,
					DialoguePrompt: "Autarch Jonti, the Khanate recognizes ambition. Renounce the Rhodian fugitives and keep Lingane.",
				},
				{
					ID:             "aratap_spectrometric_grid",
					Description:    "Map gravitational eddies within the dark dust to predict the conspirators' landing site",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"spectrometric", "eddies", "gravimetric", "mapping"},
					BaseRisk:       0.15,
					DialoguePrompt: "Calibrate the tachyon sensors to nebular density variations. They cannot hide from physics.",
				},
			},
		},
		{
			Index:        4,
			Title:        "Exposing the Linganian Gambit",
			Location:     "Nebular Orbit, Rendezvous Point",
			Description:  "Aratap springs the trap, surrounding Remembrance and Jonti's flagship with twelve heavy cruisers.",
			PrimaryActor: "simok_aratap",
			Options: []persona.CandidateAction{
				{
					ID:             "aratap_expose_jonti",
					Description:    "Reveal Jonti's original signed betrayal of the Rancher of Widemos to splinter the rebels",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"betrayal", "intel", "psychological", "order"},
					BaseRisk:       0.1,
					DialoguePrompt: "Autarch Jonti, did you truly believe the Khanate destroys its intelligence receipts? Young Farrill, look at the transmission log.",
				},
				{
					ID:             "aratap_order_fleet_salvo",
					Description:    "Order a warning volley of particle cannons across the bow of the rebel flagship",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"salvo", "cannons", "warning", "bombardment"},
					BaseRisk:       0.5,
					DialoguePrompt: "Main batteries, broadside volley across their shields! Let them understand resistance is futility.",
				},
				{
					ID:             "aratap_jam_rebel_comms",
					Description:    "Blanket the sector with broadband sub-ether jamming to prevent coordinated rebel defense",
					TacticalType:   "COVERT",
					Keywords:       []string{"jamming", "frequencies", "electronic", "blackout"},
					BaseRisk:       0.2,
					DialoguePrompt: "Engage blanket carrier jamming. Isolate each ship in absolute silence.",
				},
				{
					ID:             "aratap_cross_examine_conspirators",
					Description:    "Dismantle Jonti's lies through rigorous cross-examination before the gathered officers",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"interrogate", "truth", "logic", "deduction"},
					BaseRisk:       0.15,
					DialoguePrompt: "Explain the discrepancy between your declared flight manifest and this Imperial payment record, Autarch.",
				},
			},
		},
		{
			Index:        5,
			Title:        "The Lesson of the Parchment",
			Location:     "Flagship Council Chamber",
			Description:  "The mysterious rebellion weapon is unveiled as ancient Terra's democratic Constitution. Aratap reflects on the philosophical nature of imperial rule.",
			PrimaryActor: "simok_aratap",
			Options: []persona.CandidateAction{
				{
					ID:             "aratap_philosophical_verdict",
					Description:    "Acknowledge the historical inevitability of democratic integration and avoid planetary slaughter",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"rationality", "historical", "governance", "future"},
					BaseRisk:       0.2,
					DialoguePrompt: "A paper constitution... No battleships, no planet-busters. You may keep your ancient parchment, Farrill. Let us see if human nature can live up to it.",
				},
				{
					ID:             "aratap_confiscate_parchment",
					Description:    "Seize the document by imperial decree and declare democratic literature treasonous contraband",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"confiscate", "treason", "contraband", "decree"},
					BaseRisk:       0.6,
					DialoguePrompt: "This seditious parchment is confiscated in the name of the Khan. Any planet printing it faces orbital censure.",
				},
				{
					ID:             "aratap_archive_secret_dossier",
					Description:    "Classify the document into the imperial intelligence archives to preserve imperial stability",
					TacticalType:   "COVERT",
					Keywords:       []string{"classify", "dossier", "archives", "redact"},
					BaseRisk:       0.25,
					DialoguePrompt: "Seal this record under top-secret security classification 'Level Omega'. The Khanate must not know fear.",
				},
				{
					ID:             "aratap_study_terran_institutions",
					Description:    "Conduct a deep comparative study of Pre-Atomic Earth governance versus Tyrannic administration",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"institutions", "scholarship", "comparison", "philosophy"},
					BaseRisk:       0.15,
					DialoguePrompt: "Fascinating. Separation of powers, checks and balances... I must study how long such an engine survived on ancient Earth.",
				},
			},
		},
	}
}

func buildGillbretScenes() []Scene {
	return []Scene{
		{
			Index:        1,
			Title:        "The Visisonor Recital",
			Location:     "Rhodian Court Ballroom",
			Description:  "Gillbret performs on his visisonor before the visiting Tyranni military inspectors, weaving hypnotic patterns of light and music.",
			PrimaryActor: "gillbret_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "gill_visisonor_hypnosis",
					Description:    "Project emotional harmonics to induce disorientation among the Tyranni guard officers",
					TacticalType:   "COVERT",
					Keywords:       []string{"visisonor", "music", "psychology", "genius"},
					BaseRisk:       0.25,
					DialoguePrompt: "Listen to the light, gentlemen... feel the harmony of the stars.",
				},
				{
					ID:             "gill_crescendo_disruption",
					Description:    "Unleash a piercing acoustic crescendo to trigger palace emergency alarm overrides",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"crescendo", "sound", "shockwave", "alarm"},
					BaseRisk:       0.6,
					DialoguePrompt: "Hear the fury of fifty suppressed worlds in one single chord!",
				},
				{
					ID:             "gill_diplomatic_performance",
					Description:    "Weave a gentle court melody celebrating interstellar peace to disarm Tyranni suspicions",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"harmony", "melody", "peace", "court"},
					BaseRisk:       0.15,
					DialoguePrompt: "Music knows no borders, Commissioner. It speaks what politics cannot express.",
				},
				{
					ID:             "gill_acoustical_mapping",
					Description:    "Use visisonor resonance to map concealed eavesdropping devices embedded in the ballroom walls",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"resonance", "frequencies", "mapping", "bugs"},
					BaseRisk:       0.2,
					DialoguePrompt: "Notice how the fifth harmonic bends against the east pillar... an imperial microphone is hidden there.",
				},
			},
		},
		{
			Index:        2,
			Title:        "The Secret of the Shipwreck",
			Location:     "Gillbret's Private Observatory, Rhodia",
			Description:  "Gillbret reveals the truth of his twenty-year-old hyperspace shipwreck to Biron and Artemisia.",
			PrimaryActor: "gillbret_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "gill_share_coordinates",
					Description:    "Disclose the encoded astrogation logs pointing into the Horsehead Nebula",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"coordinates", "nebula", "truth", "rebellion"},
					BaseRisk:       0.3,
					DialoguePrompt: "They called me mad! But I saw it with my own eyes—lights and vessels thriving in the deep dust!",
				},
				{
					ID:             "gill_conceal_nav_cipher",
					Description:    "Encrypt the coordinates within a musical notation sheet so only he can navigate the ship",
					TacticalType:   "COVERT",
					Keywords:       []string{"encrypt", "cipher", "musical", "secrecy"},
					BaseRisk:       0.2,
					DialoguePrompt: "The route is hidden within this sonata. Without my hands on the instruments, no cruiser can find it.",
				},
				{
					ID:             "gill_impassioned_plea",
					Description:    "Impassionately urge Biron and Artemisia to unite their fates and embark on the expedition",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"plea", "unity", "destiny", "courage"},
					BaseRisk:       0.25,
					DialoguePrompt: "Do not let my twenty years of silence be in vain! Together, we can break Tyrann's grip forever.",
				},
				{
					ID:             "gill_confront_doubters",
					Description:    "Angrily smash his telescope astrolabe to demand that Biron acknowledge the truth of his vision",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"confront", "passion", "truth", "smash"},
					BaseRisk:       0.5,
					DialoguePrompt: "Doubt me if you dare! But look at the spectral charts before you call me a lunatic!",
				},
			},
		},
		{
			Index:        3,
			Title:        "Sabotage on the Hangar Floor",
			Location:     "Rhodia Spaceport Maintenance Deck",
			Description:  "Gillbret uses acoustic tools to disable the port tracking radar array.",
			PrimaryActor: "gillbret_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "gill_disable_radar",
					Description:    "Overload radar receiver with harmonic acoustic feedback",
					TacticalType:   "COVERT",
					Keywords:       []string{"sabotage", "acoustic", "escape"},
					BaseRisk:       0.35,
					DialoguePrompt: "A simple harmonic surge in the waveguide... and Tyrann's eyes go blind.",
				},
				{
					ID:             "gill_acoustic_overload",
					Description:    "Blast the hangar intercom system with high-frequency sonic bursts to stun port sentries",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"sonic", "overload", "stun", "sentries"},
					BaseRisk:       0.55,
					DialoguePrompt: "Cover your ears! The whole hangar is about to shudder!",
				},
				{
					ID:             "gill_bluff_technicians",
					Description:    "Present forged maintenance authorization forms to the chief hangar technician",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"bluff", "authority", "inspection", "technicians"},
					BaseRisk:       0.25,
					DialoguePrompt: "Director Hinrik ordered an emergency diagnostic of the primary dish. Step back and let me inspect it.",
				},
				{
					ID:             "gill_analyze_sensor_specs",
					Description:    "Examine the radar antenna waveguides to identify blind spots in the orbital tracking network",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"waveguide", "blindspot", "sensors", "specs"},
					BaseRisk:       0.2,
					DialoguePrompt: "If we align Remembrance's vector with the solar flare shadow, this sensor model has a 12-degree blind zone.",
				},
			},
		},
		{
			Index:        4,
			Title:        "The Visisonor Duel of Minds",
			Location:     "Nebular Orbit, Aboard The Remembrance",
			Description:  "Gillbret detects deceit in Sander Jonti's aura and uses the visisonor to test the Autarch's subconscious.",
			PrimaryActor: "gillbret_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "gill_probe_jonti",
					Description:    "Channel cognitive probe chords to reveal Jonti's suppressed guilt over Widemos",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"probe", "guilt", "visisonor", "exposure"},
					BaseRisk:       0.3,
					DialoguePrompt: "Why does the Autarch flinch at the sound of the Widemos mourning chord?",
				},
				{
					ID:             "gill_visisonor_terror_wave",
					Description:    "Project a terrifying optical illusion of imperial dreadnoughts to rattle Jonti into a tactical error",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"terror", "projection", "dreadnought", "shock"},
					BaseRisk:       0.6,
					DialoguePrompt: "Look behind you, Jonti! The shadows you fear have arrived to claim your debt!",
				},
				{
					ID:             "gill_subconscious_lullaby",
					Description:    "Weave calming sub-audible rhythms to put Jonti's armed bodyguards into a stupor",
					TacticalType:   "COVERT",
					Keywords:       []string{"lullaby", "rhythms", "stupor", "sleep"},
					BaseRisk:       0.3,
					DialoguePrompt: "Close your heavy eyes, Linganian guards... dream of peace.",
				},
				{
					ID:             "gill_appeal_to_lingane_crew",
					Description:    "Appeal to the conscience of the Linganian officers through historic folk anthems of liberty",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"anthem", "liberty", "conscience", "appeal"},
					BaseRisk:       0.25,
					DialoguePrompt: "Men of Lingane! Do you follow a tyrant or do you fight for the free stars?",
				},
			},
		},
		{
			Index:        5,
			Title:        "Vindication in the Dark Cloud",
			Location:     "Flagship Council Chamber",
			Description:  "Standing before Aratap and Hinrik, Gillbret realizes the true meaning of his vision.",
			PrimaryActor: "gillbret_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "gill_claim_vindication",
					Description:    "Celebrate the vindication of his sanity and the awakening of fifty star kingdoms",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"vindication", "sanity", "liberty", "stars"},
					BaseRisk:       0.2,
					DialoguePrompt: "I was never mad! The rebellion world was not in the dust—it was in the hearts of free men!",
				},
				{
					ID:             "gill_symphonic_defiance",
					Description:    "Play a triumphant, deafening anthem through the flagship communications channels",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"anthem", "triumph", "loud", "defiance"},
					BaseRisk:       0.55,
					DialoguePrompt: "Let this music echo across every hull in the Tyranni fleet! We are free!",
				},
				{
					ID:             "gill_preserve_sensory_memories",
					Description:    "Record the historic confrontation into an indelible crystal memory for future historians",
					TacticalType:   "COVERT",
					Keywords:       []string{"crystal", "memory", "historian", "archive"},
					BaseRisk:       0.2,
					DialoguePrompt: "This moment belongs to eternity. Every note, every word is recorded in the crystalline matrix.",
				},
				{
					ID:             "gill_chart_stellar_frequencies",
					Description:    "Transcribe the nebular frequency spectrum that initially misled his navigation twenty years ago",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"spectrum", "frequencies", "astronomy", "nebula"},
					BaseRisk:       0.15,
					DialoguePrompt: "Now I understand... the nebula was refracting ancient pulsar signals from Sector Solar-0.",
				},
			},
		},
	}
}

func buildJontiScenes() []Scene {
	return []Scene{
		{
			Index:        1,
			Title:        "The Elimination of Widemos",
			Location:     "Autarch's Citadel, Lingane",
			Description:  "Sander Jonti reflects on delivering the sealed dossier on the Rancher of Widemos to Tyranni intelligence.",
			PrimaryActor: "sander_jonti",
			Options: []persona.CandidateAction{
				{
					ID:             "jonti_justify_betrayal",
					Description:    "Consolidate control over regional rebel cells now that Widemos is removed",
					TacticalType:   "COVERT",
					Keywords:       []string{"autocracy", "hegemony", "consolidation", "realpolitik"},
					BaseRisk:       0.3,
					DialoguePrompt: "Widemos was a sentimental fool. A galactic revolution requires an iron fist, not a romantic rancher.",
				},
				{
					ID:             "jonti_purge_dissidents",
					Description:    "Execute a violent internal purge of loyalist Widemos officers in the Linganian guard",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"purge", "ruthless", "iron", "discipline"},
					BaseRisk:       0.55,
					DialoguePrompt: "Any officer speaking Widemos's name will face firing squads before nightfall.",
				},
				{
					ID:             "jonti_forge_aristocratic_pact",
					Description:    "Offer secret trade concessions to Rhodian lords to ensure their compliance with his planned coup",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"pact", "aristocracy", "concessions", "alliance"},
					BaseRisk:       0.25,
					DialoguePrompt: "Tell the barons of Rhodia that Lingane guarantees their grain quotas once the Hinriads fall.",
				},
				{
					ID:             "jonti_infiltrate_widemos_files",
					Description:    "Search Widemos's seized correspondence for clues regarding the ancient super-weapon",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"files", "clues", "superweapon", "intelligence"},
					BaseRisk:       0.2,
					DialoguePrompt: "Farrill knew of a weapon capable of toppling the Khanate. Where did he hide the coordinates?",
				},
			},
		},
		{
			Index:        2,
			Title:        "Guiding the Widemos Heir",
			Location:     "Subspace Communication Hub, Lingane",
			Description:  "Jonti dispatches covert alerts to Earth to push young Biron toward Rhodia.",
			PrimaryActor: "sander_jonti",
			Options: []persona.CandidateAction{
				{
					ID:             "jonti_manipulate_biron",
					Description:    "Transmit anonymous coordinates to ensure Biron stirs up Rhodian court intrigue",
					TacticalType:   "COVERT",
					Keywords:       []string{"manipulate", "pawn", "rhodia"},
					BaseRisk:       0.25,
					DialoguePrompt: "Let young Farrill play the avenging hero and draw Aratap's gaze while we ready the fleet.",
				},
				{
					ID:             "jonti_demand_rhodian_submission",
					Description:    "Issue a veiled military ultimatum to Director Hinrik demanding an immediate summit",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"ultimatum", "pressure", "force", "threat"},
					BaseRisk:       0.6,
					DialoguePrompt: "Remind Hinrik that Linganian gunboats patrol his border. His stalling is at an end.",
				},
				{
					ID:             "jonti_diplomatic_overture_earth",
					Description:    "Send a diplomatic envoy to Earth offering scholarship subsidies to recruit promising students",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"scholarship", "envoy", "recruitment", "earth"},
					BaseRisk:       0.2,
					DialoguePrompt: "Flatter the Earth authorities. A friendly face on Earth keeps our agents unmolested.",
				},
				{
					ID:             "jonti_intercept_courier_packets",
					Description:    "Decode imperial courier packets travelling between Rhodia and the Khan's homeworld",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"decode", "intercept", "packets", "ciphers"},
					BaseRisk:       0.2,
					DialoguePrompt: "Break their encryption ciphers. I must know every move Commissioner Aratap makes.",
				},
			},
		},
		{
			Index:        3,
			Title:        "The Demand for Supremacy",
			Location:     "Space Sector Lingane-Outpost",
			Description:  "Jonti boards Remembrance and attempts to coerce Artemisia and Biron into acknowledging his supreme authority.",
			PrimaryActor: "sander_jonti",
			Options: []persona.CandidateAction{
				{
					ID:             "jonti_assert_leadership",
					Description:    "Demand sole command of the Horsehead expedition in exchange for Linganian escort",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"autocracy", "command", "supremacy"},
					BaseRisk:       0.4,
					DialoguePrompt: "I command six battle cruisers. You possess a stolen prototype. Do not mistake courtesy for weakness.",
				},
				{
					ID:             "jonti_covert_crew_sabotage",
					Description:    "Order his personal bodyguards to tamper with Remembrance's hyperdrive interlocks",
					TacticalType:   "COVERT",
					Keywords:       []string{"sabotage", "interlocks", "tamper", "control"},
					BaseRisk:       0.35,
					DialoguePrompt: "Slightly misalign their primary injector. If they try to jump without us, they stall.",
				},
				{
					ID:             "jonti_propose_joint_command",
					Description:    "Offer an equal coalition command structure to lull Biron and Artemisia into complacency",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"coalition", "diplomacy", "flattery", "compromise"},
					BaseRisk:       0.2,
					DialoguePrompt: "Let us share the burden of leadership, my friends. We are partners in this grand enterprise.",
				},
				{
					ID:             "jonti_audit_remembrance_drives",
					Description:    "Inspect the prototype drives to understand Rhodia's clandestine shipbuilding advancements",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"audit", "technology", "inspection", "cruiser"},
					BaseRisk:       0.15,
					DialoguePrompt: "These drive schematics are decades ahead of standard imperial craft. How did Hinrik build this?",
				},
			},
		},
		{
			Index:        4,
			Title:        "The Unraveling Conspiracy",
			Location:     "Inside the Horsehead Nebula",
			Description:  "Aratap's imperial battlefleet surrounds the flotilla, and the sub-ether tracking device is identified.",
			PrimaryActor: "sander_jonti",
			Options: []persona.CandidateAction{
				{
					ID:             "jonti_feign_innocence",
					Description:    "Blame Rhodia for the sub-ether bug and draw blaster to seize Biron as hostage",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"hostage", "blaster", "survival"},
					BaseRisk:       0.8,
					DialoguePrompt: "Farrill! You led them to us! Back away or I disintegrate the girl!",
				},
				{
					ID:             "jonti_covert_escape_pod",
					Description:    "Slip toward the auxiliary escape pods while the fleets maneuver",
					TacticalType:   "COVERT",
					Keywords:       []string{"escape", "pod", "stealth", "survival"},
					BaseRisk:       0.4,
					DialoguePrompt: "Quietly detach the pod. Let the fools fight each other while I vanish into the dark nebula.",
				},
				{
					ID:             "jonti_appeal_to_aratap",
					Description:    "Hail Commissioner Aratap to negotiate immunity by handing over Biron and Artemisia",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"negotiate", "immunity", "plea", "turncoat"},
					BaseRisk:       0.3,
					DialoguePrompt: "Commissioner Aratap! I delivered the conspirators into your hands as arranged! Acknowledge our accord!",
				},
				{
					ID:             "jonti_scan_sensor_shadows",
					Description:    "Calculate sensor blind zones in the Tyranni fleet formation to find an escape window",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"sensors", "blindzone", "astronomy", "tactics"},
					BaseRisk:       0.25,
					DialoguePrompt: "Their third cruiser squadron is lagged by five degrees... there is a gap in their interlock grid.",
				},
			},
		},
		{
			Index:        5,
			Title:        "The Fall of the Autarch",
			Location:     "Imperial Interrogation Deck",
			Description:  "Disarmed and exposed by Aratap's decrypted receipts, Jonti faces total political ruin.",
			PrimaryActor: "sander_jonti",
			Options: []persona.CandidateAction{
				{
					ID:             "jonti_final_curse",
					Description:    "Curse democratic idealism and predict the collapse of all fifty kingdoms into barbarian ruin",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"autocracy", "cynicism", "ruin"},
					BaseRisk:       0.2,
					DialoguePrompt: "You are children! When the Khanate falls, your 'democracy' will drown in blood within a generation!",
				},
				{
					ID:             "jonti_stoic_silence",
					Description:    "Refuse to utter a single word, denying Aratap and Farrill any emotional victory",
					TacticalType:   "COVERT",
					Keywords:       []string{"silence", "stoic", "refusal", "pride"},
					BaseRisk:       0.25,
					DialoguePrompt: "...",
				},
				{
					ID:             "jonti_conditional_confession",
					Description:    "Offer to testify against rogue Tyranni governors in exchange for exile on a remote estate",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"confession", "exile", "testimony", "deal"},
					BaseRisk:       0.3,
					DialoguePrompt: "I know which of your viceroys took Widemos gold, Aratap. I can name names—for a price.",
				},
				{
					ID:             "jonti_dissect_aratap_strategy",
					Description:    "Analytically dissect Aratap's counter-strategy to expose its eventual institutional failure",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"critique", "strategy", "history", "imperium"},
					BaseRisk:       0.2,
					DialoguePrompt: "You played your hand well, Commissioner. But an empire that relies on the mercy of paper is already dying.",
				},
			},
		},
	}
}

func buildHinrikScenes() []Scene {
	return []Scene{
		{
			Index:        1,
			Title:        "The Mask of Incompetence",
			Location:     "Director's Solar, Rhodia",
			Description:  "Director Hinrik rehearses his nervous stammer and prepares for Commissioner Aratap's unscheduled audit.",
			PrimaryActor: "hinrik_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "hinrik_play_fool",
					Description:    "Fidget frantically with medical tonics and complaints to divert Aratap from archival activities",
					TacticalType:   "COVERT",
					Keywords:       []string{"mask", "folly", "survival", "camouflage"},
					BaseRisk:       0.1,
					DialoguePrompt: "Oh dear, my nervous palpitations again... where did the physician place the sedative drops?",
				},
				{
					ID:             "hinrik_demand_imperial_respect",
					Description:    "Momentarily adopt an authoritarian posture demanding the Commissioner respect Rhodian domestic autonomy",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"sovereignty", "authority", "respect", "demand"},
					BaseRisk:       0.6,
					DialoguePrompt: "Commissioner Aratap, the Directorate is an allied realm, not a conquered province!",
				},
				{
					ID:             "hinrik_cordial_welcome",
					Description:    "Host an elaborate state banquet to flatter Aratap and delay the archival inspection",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"banquet", "flattery", "hospitality", "diplomacy"},
					BaseRisk:       0.2,
					DialoguePrompt: "Welcome to Rhodia, Commissioner. Join us at table before we attend to tedious paperwork.",
				},
				{
					ID:             "hinrik_gauge_aratap_suspicion",
					Description:    "Quietly observe Aratap's micro-expressions to gauge what imperial intelligence already suspects",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"observation", "microexpressions", "deduction", "intelligence"},
					BaseRisk:       0.15,
					DialoguePrompt: "He glanced twice at the north vault manifests... they suspect an information leak.",
				},
			},
		},
		{
			Index:        2,
			Title:        "Shielding Artemisia",
			Location:     "Private Corridor, Rhodian Palace",
			Description:  "Hinrik overhears his daughter Artemisia expressing bitter shame over his apparent cowardice.",
			PrimaryActor: "hinrik_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "hinrik_endure_scorn",
					Description:    "Swallow the agony of his daughter's contempt to keep her off the Tyranni execution list",
					TacticalType:   "DEFENSIVE",
					Keywords:       []string{"sacrifice", "patience", "protection"},
					BaseRisk:       0.15,
					DialoguePrompt: "Despise me if you must, my sweet child... but live. Live until the day the chains break.",
				},
				{
					ID:             "hinrik_subtle_warning_whisper",
					Description:    "Slip a ciphered warning token into her pocket cautioning her against palace informants",
					TacticalType:   "COVERT",
					Keywords:       []string{"token", "cipher", "warning", "stealth"},
					BaseRisk:       0.2,
					DialoguePrompt: "Take this pendant, Artemisia. When danger closes in, trust only its seal.",
				},
				{
					ID:             "hinrik_embrace_daughter",
					Description:    "Gently console Artemisia with veiled metaphors of Rhodia's ancestral endurance",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"comfort", "endurance", "metaphor", "heritage"},
					BaseRisk:       0.2,
					DialoguePrompt: "The mighty oak breaks in the gale, my daughter; the humble willow bends and rises again.",
				},
				{
					ID:             "hinrik_probe_palace_microphones",
					Description:    "Conduct a covert sweep of the corridor conduits to identify Tyranni surveillance sensors",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"sweep", "conduits", "surveillance", "sensors"},
					BaseRisk:       0.2,
					DialoguePrompt: "Three active transmitter relays within twenty paces... the walls themselves have ears tonight.",
				},
			},
		},
		{
			Index:        3,
			Title:        "Unlocking the Hangar Vault",
			Location:     "Deep Vault beneath Spaceport 9",
			Description:  "Hinrik secretly overrides the security interlocks on prototype cruiser Remembrance, ensuring Biron can access it.",
			PrimaryActor: "hinrik_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "hinrik_enable_escape",
					Description:    "Key in the master clearance bypass and slip the coordinates into Biron's navigation console",
					TacticalType:   "COVERT",
					Keywords:       []string{"bypass", "vault", "rebellion", "constitutional"},
					BaseRisk:       0.25,
					DialoguePrompt: "Widemos died for this dream. Go, young Biron, and carry humanity forward.",
				},
				{
					ID:             "hinrik_shut_hangar_security_grid",
					Description:    "Trigger an emergency overload in the hangar security power grid to trap pursuers",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"overload", "trap", "grid", "sabotage"},
					BaseRisk:       0.5,
					DialoguePrompt: "Drop the primary blast bulkheads! Lock the Tyranni inspectors in sub-level four!",
				},
				{
					ID:             "hinrik_distract_port_commandant",
					Description:    "Engage the spaceport commandant in an urgent bureaucratic dispute regarding fuel taxes",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"distract", "commandant", "taxes", "bureaucracy"},
					BaseRisk:       0.2,
					DialoguePrompt: "Commandant, look at these discrepancy figures! We cannot authorize departures until tariffs are reconciled!",
				},
				{
					ID:             "hinrik_verify_remembrance_jump_logs",
					Description:    "Examine Remembrance's hyperdrive chronometer calibrations to ensure safe nebular transit",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"chronometer", "calibrations", "diagnostics", "hyperdrive"},
					BaseRisk:       0.15,
					DialoguePrompt: "The chronometer drift is within 0.002 milliseconds. The coordinates will hold true in deep hyperspace.",
				},
			},
		},
		{
			Index:        4,
			Title:        "The Great Deception Disclosed",
			Location:     "Directorate Archive Chamber",
			Description:  "Aratap demands the surrender of the suspected rebellion base coordinates.",
			PrimaryActor: "hinrik_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "hinrik_deliver_document",
					Description:    "Drop the stammering facade, straighten his spine, and present the ancient Pre-Atomic Earth Constitution",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"constitutional", "revelation", "truth", "sovereignty"},
					BaseRisk:       0.2,
					DialoguePrompt: "Look well upon me, Commissioner Aratap. For thirty years I have played the clown so this parchment might live. Here is the true weapon.",
				},
				{
					ID:             "hinrik_defiant_ultimatum",
					Description:    "Order palace royal guards to level blasters at Aratap's escort delegation",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"defiance", "blasters", "ultimatum", "arrest"},
					BaseRisk:       0.7,
					DialoguePrompt: "You are standing on Rhodian soil, Commissioner! Disarm your escort or you will not leave this chamber alive!",
				},
				{
					ID:             "hinrik_conceal_second_charter",
					Description:    "Provide Aratap with a decoy coordinate cylinder while keeping the true planetary charter hidden",
					TacticalType:   "COVERT",
					Keywords:       []string{"decoy", "conceal", "misdirection", "cylinder"},
					BaseRisk:       0.3,
					DialoguePrompt: "Take the cylinder, Aratap... but know that the true charter remains safely beyond your reach.",
				},
				{
					ID:             "hinrik_interrogate_imperial_jurisdiction",
					Description:    "Challenge Aratap's legal authority under the ancient interstellar covenants",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"jurisdiction", "covenants", "law", "inquiry"},
					BaseRisk:       0.2,
					DialoguePrompt: "Cite the treaty clause, Commissioner, that permits the Khan to confiscate sovereign historical archives.",
				},
			},
		},
		{
			Index:        5,
			Title:        "The New Dawn for the Fifty Kingdoms",
			Location:     "Directorate Balcony, Rhodia",
			Description:  "With Jonti disgraced and Aratap withdrawing his garrison, Hinrik addresses the free worlds.",
			PrimaryActor: "hinrik_hinriad",
			Options: []persona.CandidateAction{
				{
					ID:             "hinrik_federation_dawn",
					Description:    "Proclaim the constitutional assembly of the fifty star kingdoms",
					TacticalType:   "DIPLOMATIC",
					Keywords:       []string{"federation", "democracy", "constitution", "dawn"},
					BaseRisk:       0.1,
					DialoguePrompt: "Let the stars shine like dust across the black sky—not as isolated tyrannies, but as a commonwealth of free peoples.",
				},
				{
					ID:             "hinrik_assert_system_defenses",
					Description:    "Mobilize Rhodia's planetary defense batteries to deter any future Khanate reprisal",
					TacticalType:   "AGGRESSIVE",
					Keywords:       []string{"defenses", "batteries", "mobilize", "deterrence"},
					BaseRisk:       0.4,
					DialoguePrompt: "Power up all orbital fortress batteries! Rhodia will never again bow to any emperor!",
				},
				{
					ID:             "hinrik_establish_secret_council",
					Description:    "Appoint a covert intelligence council to monitor lingering Linganian and Tyranni revanchists",
					TacticalType:   "COVERT",
					Keywords:       []string{"intelligence", "watchdogs", "vigilance", "council"},
					BaseRisk:       0.2,
					DialoguePrompt: "Freedom requires vigilance. Establish shadow observation posts on every border sector.",
				},
				{
					ID:             "hinrik_codify_planetary_charters",
					Description:    "Begin drafting the legal translation of ancient Earth constitutional articles for all fifty planetary systems",
					TacticalType:   "INQUISITIVE",
					Keywords:       []string{"codify", "articles", "scholarship", "charter"},
					BaseRisk:       0.1,
					DialoguePrompt: "Call the scholars and jurists. We have a galactic federation of laws to construct.",
				},
			},
		},
	}
}
